[package]
name = "bevy_skybox"
description = "A skybox from an image for bevyengine.org"
version = "0.1.0"
authors = ["Jonathan Lawn <Jonathan.M.Lawn@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
bevy = "0.4"
image = "0.23"
itertools = "0.10"

[dev-dependencies]
bevy_fly_camera = "0.6"
rand = "0.8"